require('dotenv').config();

/** @type {import('next').NextConfig} */
const nextConfig = {
    env: {
        APPWRITE_ENDPOINT: process.env.APPWRITE_ENDPOINT,
        APPWRITE_PROJECT_ID: process.env.APPWRITE_PROJECT_ID,
        APPWRITE_DATABASE_ID: process.env.APPWRITE_DATABASE_ID,
        APPWRITE_COLLECTION_GAMES_ID: process.env.APPWRITE_COLLECTION_GAMES_ID,
        APPWRITE_COLLECTION_PLAYERS_ID: process.env.APPWRITE_COLLECTION_PLAYERS_ID,
        APPWRITE_FUNCTION_SEARCH_GAME_ID: process.env.APPWRITE_FUNCTION_SEARCH_GAME_ID,
        APPWRITE_FUNCTION_START_GAME_ID: process.env.APPWRITE_FUNCTION_START_GAME_ID,
        APPWRITE_FUNCTION_JOIN_GAME_ID: process.env.APPWRITE_FUNCTION_JOIN_GAME_ID,
        APPWRITE_FUNCTION_CREATE_GAME_ID: process.env.APPWRITE_FUNCTION_CREATE_GAME_ID,
        APPWRITE_FUNCTION_VOTE_EVENT_ID: process.env.APPWRITE_FUNCTION_VOTE_EVENT_ID
    }
}

module.exports = nextConfig
